# Generated by Django 4.1.6 on 2023-02-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65536)),
                ('authors', models.CharField(max_length=65536)),
                ('year', models.IntegerField()),
                ('citation', models.CharField(max_length=65536)),
                ('keywords', models.CharField(max_length=65536)),
                ('abstract', models.CharField(max_length=65536)),
                ('ai_abstract', models.CharField(max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=65536)),
                ('source', models.IntegerField()),
                ('keywords', models.CharField(max_length=65536)),
                ('paraphrased', models.IntegerField()),
            ],
        ),
    ]
