# Generated by Django 4.1.6 on 2023-02-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default='', max_length=65536),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insight',
            name='location',
            field=models.CharField(default='', max_length=65536),
            preserve_default=False,
        ),
    ]
