# Generated by Django 4.1.6 on 2023-03-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_article_tags_insight_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='keywords',
        ),
    ]
